### ISSUE TITLE
I have a problem with Houdini-asyncio

### ISSUE THREAD

**Issue by sparkbg** [Solero/Houdini-asyncio#15]
I'm having a problem with Houdini-asyncio typing this command in the pip install -r requirements terminal.txt I get this error
![Untitled](https://user-images.githubusercontent.com/39089661/78468708-0a625a80-7723-11ea-8f70-2123c0e23670.png)

**Comment by ketnipz** [comment]
Read the error: "aioredis doesn't support Python version prior 3.5"

You are trying to use a python version lower than 3.5. Houdini-asynio supports versions 3.8 and up.

This is not an issue with Houdini so I'm going to close this issue. If you need help with setup please [join the discord](https://solero.me/discord) and ask in the #support channel.

**Comment by sparkbg** [comment]
Mercy for help I fixed this error I have one last question as I type the python bootstrap.py login command this error appears in the console
![Untitled](https://user-images.githubusercontent.com/39089661/78475441-d734c100-774c-11ea-9505-237d56620de0.png)
