### ISSUE TITLE
Single client mode breaks world server

### ISSUE THREAD

**Issue by daniel11420** [solero/houdini-asyncio#19]
World server will give an igloo-related asyncpg error when trying to join the world server (login works fine) if --single-client-mode flag is present. Removing this flag fixes it.

**Comment by ketnipz** [comment]
I believe this to be caused by assignment of the client type when signing in while server is in single client mode.

Please see my linked pull request and confirm this fixed this issue before I merge into the master branch.

**Comment by daniel11420** [comment]
Yes, the PR fixes the issue.
