### ISSUE TITLE
I made my own club penguin server out of localhost | Aka XAMMP

### ISSUE THREAD

**Issue by Orbit4682** [Solero/Houdini-asyncio#2]
I want to change my localhost link for people to play on. Plus i need to connect a vps on my server. I will use Hamachi, Please help me to do these! 

-Club Penguin Force Staff

**Comment by ketnipz** [comment]
Not even an issue regarding Houdini-asyncio.

Please join our [Discord server](https://solero.me/discord) if you are confused or have any questions.
