### ISSUE TITLE
phpmyadmin import error

### ISSUE THREAD

**Issue by geometry88** [solero/houdini-asyncio#23]
error

![Безымянный](https://user-images.githubusercontent.com/16748478/81349911-9cb2a100-90c9-11ea-8106-1594b41191a2.png)
![Безымянный2](https://user-images.githubusercontent.com/16748478/81350039-d2578a00-90c9-11ea-88ca-4e9dce3b5c65.png)

**Comment by ketnipz** [comment]
Hi, houdini-asyncio does not use MySQL. It uses PostgreSQL

Please see https://github.com/solero/wand
