### ISSUE TITLE
Stealth Mod invisibility

### ISSUE THREAD

**Issue by PaXo0** [solero/houdini-asyncio#27]
When a penguin is set as stealth moderator and is already in a room when another penguin enters that room they are able to view the invisible penguin and also continues to see it when the stealth penguin has left.

Running AS3 client / vanilla

**Comment by ketnipz** [comment]
Was able to replicate this and created a pull request with my fix.

Please could someone test that this resolves the issue before I merge with  master branch.

**Comment by Jaskowicz1** [comment]
Works.
